### ISSUE TITLE
How to read json file, after run this code it can't read the json file

### ISSUE THREAD

**Issue by RAJANAGORI** [DataTurks-Engg/Entity-Recognition-In-Resumes-SpaCy#11]
In the repo you have given json file and when i run the code it can't read the json file.
it just simply loading the juPYTER notebook after the main function call  and when i run on pycharm it throw the error

**ERROR:root:Unable to process traindata.json
error = 'NoneType' object is not iterable
Traceback (most recent call last):
  File "train.py", line 22, in convert_dataturks_to_spacy
    for annotation in data['annotation']:
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "train.py", line 123, in <module>
    train_spacy()
  File "train.py", line 53, in train_spacy
    for _, annotations in TRAIN_DATA:
TypeError: 'NoneType' object is not iterable**

ERROR:root:Unable to process traindata.json
error = 'NoneType' object is not iterable
Traceback (most recent call last):
  File "<ipython-input-13-5c68f18e0c52>", line 12, in convert_dataturks_to_spacy
    for annotation in data['annotation']:
TypeError: 'NoneType' object is not iterable

**Comment by marcoseoane** [comment]
im having the same problem

**Comment by mrpacino** [comment]
so i had this problem at first, changed the file path in train.py to point to the testdata.json in the folder, then got this error:

Statring iteration 0
Traceback (most recent call last):
  File "train.py", line 132, in <module>
    train_spacy()
  File "train.py", line 79, in train_spacy
    losses=losses)
  File "/Users/marcoseoane/.local/share/virtualenvs/ner-sandbox-2vOtzlAl/lib/python3.7/site-packages/spacy/language.py", line 457, in update
    proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
  File "nn_parser.pyx", line 413, in spacy.syntax.nn_parser.Parser.update
  File "nn_parser.pyx", line 519, in spacy.syntax.nn_parser.Parser._init_gold_batch
  File "transition_system.pyx", line 86, in spacy.syntax.transition_system.TransitionSystem.get_oracle_sequence
  File "transition_system.pyx", line 148, in spacy.syntax.transition_system.TransitionSystem.set_costs
ValueError: [E024] Could not find an optimal move to supervise the parser. Usually, this means the GoldParse was not correct. For example, are all labels added to the model?

**Comment by RAJANAGORI** [comment]
> so i had this problem at first, changed the file path in train.py to point to the testdata.json in the folder, then got this error:
> 
> Statring iteration 0
> Traceback (most recent call last):
> File "train.py", line 132, in 
> train_spacy()
> File "train.py", line 79, in train_spacy
> losses=losses)
> File "/Users/marcoseoane/.local/share/virtualenvs/ner-sandbox-2vOtzlAl/lib/python3.7/site-packages/spacy/language.py", line 457, in update
> proc.update(docs, golds, sgd=get_grads, losses=losses, **kwargs)
> File "nn_parser.pyx", line 413, in spacy.syntax.nn_parser.Parser.update
> File "nn_parser.pyx", line 519, in spacy.syntax.nn_parser.Parser._init_gold_batch
> File "transition_system.pyx", line 86, in spacy.syntax.transition_system.TransitionSystem.get_oracle_sequence
> File "transition_system.pyx", line 148, in spacy.syntax.transition_system.TransitionSystem.set_costs
> ValueError: [E024] Could not find an optimal move to supervise the parser. Usually, this means the GoldParse was not correct. For example, are all labels added to the model?

i didn't get you, could you please elaborate more ?
